# permissions for end users to edit flinkclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flinkcluster-editor-role
rules:
- apiGroups:
  - cluster.miaohong.org
  resources:
  - flinkclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.miaohong.org
  resources:
  - flinkclusters/status
  verbs:
  - get
